import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
const inter = Inter({ subsets: ["latin"] });

//Meta Data
export const metadata: Metadata = {
  title: {
    default: "Next.js - Redemple", // Title of the page as it appears in the browser tab
    template: "%s - Redemple", // Template for the title, will replace %s with the actual title
  },
  description: "Generated by Redemple", // Description of the page
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
